export const POPULAR_VIDEOS_SUCCESS = 'POPULAR_VIDEOS_SUCCESS'
export const POPULAR_VIDEOS_FAIL = 'POPULAR_VIDEOS_FAIL'
export const POPULAR_VIDEOS_REQUEST = 'POPULAR_VIDEOS_REQUEST'


export const CATEGORIES_VIDEOS_SUCCESS = 'CATEGORIES_VIDEOS_SUCCESS'
export const CATEGORIES_VIDEOS_FAIL = 'CATEGORIES_VIDEOS_FAIL'
export const CATEGORIES_VIDEOS_REQUEST = 'CATEGORIES_VIDEOS_REQUEST'